name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint

      - name: Build project
        run: bun run build

      - name: Run tests
        run: bun run test

      - name: Package action
        run: bun run package

      - name: Check dist is up to date
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --exit-code dist/
            echo "Run 'bun run package' and commit the changes."
            exit 1
          fi

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test action
        uses: ./
        with:
          account-name: "Test Account"
          author-name: "CI Test"
          include-patterns: "README.md"
          output-file: "test-output.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
