name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Package action
        run: yarn package

      - name: Check dist is up to date
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --exit-code dist/
            echo "Run 'yarn package' and commit the changes."
            exit 1
          fi

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Test action
        uses: ./
        with:
          account-name: "Test Account"
          author-name: "CI Test"
          include-patterns: "README.md"
          output-file: "test-output.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
