name: Convert Docs to Telegraph

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  convert-to-telegraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Telegraph mappings
        uses: actions/cache@v3
        with:
          path: telegraph-pages.json
          key: telegraph-mappings-${{ hashFiles('docs/**/*.md', 'README.md') }}
          restore-keys: |
            telegraph-mappings-

      - name: Convert markdown to Telegraph
        uses: cyanxiao/md-to-telegraph-action@release
        with:
          account-name: "md-to-telegraph-action"
          author-name: "Cyan Xiao"
          telegraph-token: "${{ secrets.TELEGRAPH_TOKEN }}"
          author-url: "https://github.com/${{ github.repository }}"
          include-patterns: "docs/**/*.md,README.md"
          exclude-patterns: "node_modules/**,dist/**"
          output-file: "telegraph-pages.json"
          one-entry-mode: "true"
          replace-existing-pages: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_LINK_TOKEN }}
